ibm:
  mq:
    queueManager: QM1
    channel: DEV.ADMIN.SVRCONN
    connName: ibm-routes-sudhir6969-dev.apps.sandbox-m3.1530.p1.openshiftapps.com
    host: ibm-routes-sudhir6969-dev.apps.sandbox-m3.1530.p1.openshiftapps.com
    port: 9443
    user: admin
    password: passw0rd
  queues:
    sampleQueues: MQCLIENT_MQ1.RESPONSE.FROM.MQSERVER_MQ2,MQCLIENT_MQ1.RESPONSE.FROM.MQSERVER_MQ1

demo:
  concurrency:
    size:
      low: 1
      high: 6
      
my:
  name: sangram
server:
  port: 4056