apiVersion: v1
kind: Pod
metadata:
  name: ibm-mq
  labels:
    app: ibm-mq       
spec:
  containers:                            
  - env:                                 
    - name: LICENSE
      value: accept
    - name: MQ_QMGR_NAME
      value: QM1
    image: 'docker.io/ibmcom/mq'
    imagePullPolicy: IfNotPresent
    name: ibm-mq
    ports:                              
    - containerPort: 1414
      protocol: TCP
    - containerPort: 9443
      protocol: TCP
    resources: {}
    securityContext: { ... }            
    readOnly: true
  restartPolicy: Always                 
  serviceAccount: default               
  volumes: 
  name: ibm-mq                             
---
   
kind: Service
apiVersion: v1
metadata:
  name: ibm-mq
spec:
  type: NodePort
  ports:
    - name: admin
      protocol: TCP
      port: 9443
      targetPort: 9443
    - name: application
      protocol: TCP
      port: 1414
      targetPort: 1414
  selector:
    app: ibm-mq

---
